fix IN operator to use OR instead of AND
khaledosama999/algolia-filter-query-builder pull request #9
Opened 2022-03-23 11:47 UTC by realiarthur

2022-03-23 12:34 UTC, khaledosama999 requested changes

2022-03-23 12:34 UTC, khaledosama999 commented on src/operators/in.ts
> +    return orOperator.exec();
Update the comment on line 12 please, so it says it resembles `an or operator`

2022-03-23 12:35 UTC, khaledosama999 commented
@realiarthur Overall great job I just have one minor request instead of using `git commit` to commit please run `npm run git-cz` and add a fix commit, I will merge it on dev and then create a release

2022-03-24 14:42 UTC, realiarthur commented
@khaledosama999 I have updated everything that you said. Thank you!

2022-03-24 16:10 UTC, khaledosama999 commented
@realiarthur  Approved, will make a new release with your fix

2022-03-24 16:10 UTC, khaledosama999 approved these changes

2022-03-24 16:33 UTC, merged

2022-03-24 16:44 UTC, khaledosama999 commented
Github actions is down, release will be up when it's back